### ISSUE TITLE
json error is coming 

### ISSUE THREAD

**Issue by flik** [davgothic/AjaxFileUpload#10]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by nlounds** [comment]
I am getting the same or a very similar error.  It only occurs on the server, not when we're developing on our local machines.

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)

**Comment by davgothic** [comment]
I cannot reproduce this issue. It is likely that @nlounds is correct and you are accidentally sending malformed JSON to the browser.

Closing for now.
