### ISSUE TITLE
The name of the plugin ('AjaxFileUpload') isn’t proper.

### ISSUE THREAD

**Issue by x-cold** [davgothic/AjaxFileUpload#12]
In fact, the plugin depends on `iframe` rather than `ajax`，which perplexs me alot.

**Comment by Erutan409** [comment]
Well, considering that AJAX stands for **A**synchronous **J**avaScript & **X**ML, wouldn't the typical usage of the practice mean that the aforementioned acronym is a misnomer, anyway?

I think by now most developers refer to the term/practice as a standard way of processing requests without reloading the main page for user experience/aesthetics.  Which, is what this plugin aims for; IMHO.

**Comment by davgothic** [comment]
It was just a name that made sense back in the day due to people requiring a method to upload files which appeared to be via AJAX.

The name has stuck around for so long I'm not sure I'd be comfortable changing it now.
