### ISSUE TITLE
deal with : Unexpected token < in JSON at position 0 

### ISSUE THREAD

**Issue by bestFeeling** [davgothic/AjaxFileUpload#15]
in Google Chrome  61.0.3163.100, server use tomcat

here I upload a file and server return a jsonstring like this
`{"error":"","hasError":false,"results":0,"rows":[]}`

and in your code 
`response = doc.body.innerHTML;`

response will be like this 
`<pre style="word-wrap: break-word; white-space: pre-wrap;">{"error":"","hasError":false,"results":0,"rows":[]}</pre>`

and next $.parseJSON cant parse it and get the error:
Unexpected token < in JSON at position 0

and I fixed it with :
`try{`
	`response = $.parseJSON(response);`
`} catch (e) {`
        `var preIndex = response.indexOf('{')`
	`var lastIndex = response.indexOf('}') + 1`
	`response = $.parseJSON(response.substring(preIndex, lastIndex));`
`}`

**Comment by davgothic** [comment]
I cannot reproduce the problem. What is the value of the content-type response header?
