### ISSUE TITLE
Not working in Microsoft Edge

### ISSUE THREAD

**Issue by mayank-mehrotra** [davgothic/AjaxFileUpload#16]
It's not working in microsoft edge. Also, sometimes create issues in chrome, safari. Please, help regarding this how I can make it's AJAX request compatible with all browsers. Thanks

**Comment by davgothic** [comment]
I've just tested the demo locally using Edge 16 and it seems to work as expected.

Could you provide more details as to how it's not working? What version of Edge? Are there any errors in the development console?
