### ISSUE TITLE
HI,i was involved in  a strange situation

### ISSUE THREAD

**Issue by licongmu** [davgothic/AjaxFileUpload#6]
when i use ajaxFileUpload in IE11,it enter in success callback function,but the data(it is the params) is "false",thus i ask my friend for helping,when he use it in IE11(his computer),he got it working normally,what's wrong?

**Comment by china-iamk** [comment]
IE11 has given prompt you.
sorry,My English is poor

**Comment by licongmu** [comment]
Hm...
sorry,i don't get either prompt indeed

**Comment by china-iamk** [comment]
demo is OK?

**Comment by licongmu** [comment]
i don't know.i couldn't use PHP.
i made it Coordinate with JAVA.

**Comment by china-iamk** [comment]
With wamp php built environment and test demo.
If OK，It may not be a problem js.
I have no contact with java

**Comment by licongmu** [comment]
ok,i gonna try it, thanks.

**Comment by china-iamk** [comment]
That's nothing.
