### ISSUE TITLE
this plug-in can used  by jQuery version 2

### ISSUE THREAD

**Issue by moxiaozhou** [davgothic/AjaxFileUpload#8]
i'm not sure this plug-in can be sued in my project ,my environment is jQuery 2.1.3.

**Comment by Nick-PAN** [comment]
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (http://localhost:8080/ajaxfileupload/demos/jquery-1.6.1.min.js:16:11363)
    at HTMLIFrameElement.onComplete (http://localhost:8080/ajaxfileupload/jquery.ajaxfileupload.js:81:18)
    at HTMLIFrameElement.handle (http://localhost:8080/ajaxfileupload/demos/jquery-1.6.1.min.js:17:1034)
    at HTMLIFrameElement.k (http://localhost:8080/ajaxfileupload/demos/jquery-1.6.1.min.js:16:30197)

**Comment by khubbaib** [comment]
did you return valid JSON from your PHP script some time its cause the issue like this..

**Comment by Nick-PAN** [comment]
i just run the demo on tomcat.

2016-11-23 

pchsbuaa 



发件人：khubbaib <notifications@github.com>
发送时间：2016-11-23 07:58
主题：Re: [davgothic/AjaxFileUpload] this plug-in can used by jQuery version 2 (#8)
收件人："davgothic/AjaxFileUpload"<AjaxFileUpload@noreply.github.com>
抄送："Nick-PAN"<pchsbuaa@sina.com>,"Comment"<comment@noreply.github.com>

did you return valid JSON from your PHP script some time its cause the issue like this..

**Comment by khubbaib** [comment]
So you are using JSP or ASP?

**Comment by khubbaib** [comment]
Demo have PHP code so try it with WAMP server or xamp

**Comment by Nick-PAN** [comment]
ok，thanks!

2016-11-23 

pchsbuaa 



发件人：khubbaib <notifications@github.com>
发送时间：2016-11-23 10:23
主题：Re: [davgothic/AjaxFileUpload] this plug-in can used by jQuery version 2 (#8)
收件人："davgothic/AjaxFileUpload"<AjaxFileUpload@noreply.github.com>
抄送："Nick-PAN"<pchsbuaa@sina.com>,"Comment"<comment@noreply.github.com>

Demo have PHP code so try it with WAMP server or xamp
